# SPDX-FileCopyrightText: 2020-2024 Nextcloud GmbH and Nextcloud contributors
# SPDX-License-Identifier: AGPL-3.0-or-later OR GPL-2.0-only

name: Check

on:
    pull_request:
        branches: [ master, stable-* ]

# Declare default permissions as read only.
permissions: read-all

concurrency:
    group: check-kotlin-${{ github.head_ref || github.run_id }}
    cancel-in-progress: true

jobs:
    check:
        runs-on: ubuntu-latest
        strategy:
            fail-fast: false
            matrix:
                task: [ detekt, spotlessKotlinCheck ]
        steps:
            -   uses: actions/checkout@08eba0b27e820071cde6df949e0beb9ba4906955 # v4.3.0
            -   name: Set up JDK 17
                uses: actions/setup-java@c5195efecf7bdfc987ee8bae7a71cb8b11521c00 # v4.7.1
                with:
                    distribution: "temurin"
                    java-version: 17
            -   name: Check ${{ matrix.task }}
                run: ./gradlew ${{ matrix.task }}
