name: "Detect new java files"

on:
    pull_request:
        branches: [ master, stable-* ]

# Declare default permissions as read only.
permissions: read-all

jobs:
    detectNewJavaFiles:
        runs-on: ubuntu-latest

        steps:
            -   uses: trilom/file-changes-action@v1.2.4
            -   uses: actions/checkout@v2
            -   name: Detect new java files
                run: scripts/analysis/detectNewJavaFiles.sh
